/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result, EventFragment } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export interface ChirpCityInterface extends utils.Interface {
  functions: {
    "chirp(string)": FunctionFragment;
    "chirps(uint256)": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "chirp", values: [string]): string;
  encodeFunctionData(
    functionFragment: "chirps",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "chirp", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "chirps", data: BytesLike): Result;

  events: {
    "Chirped(address,uint256,uint256,string)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "Chirped"): EventFragment;
}

export type ChirpedEvent = TypedEvent<
  [string, BigNumber, BigNumber, string],
  { from: string; id: BigNumber; timestamp: BigNumber; message: string }
>;

export type ChirpedEventFilter = TypedEventFilter<ChirpedEvent>;

export interface ChirpCity extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: ChirpCityInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    chirp(
      message: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    chirps(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [string, BigNumber, string] & {
        from: string;
        timestamp: BigNumber;
        message: string;
      }
    >;
  };

  chirp(
    message: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  chirps(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    [string, BigNumber, string] & {
      from: string;
      timestamp: BigNumber;
      message: string;
    }
  >;

  callStatic: {
    chirp(message: string, overrides?: CallOverrides): Promise<void>;

    chirps(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [string, BigNumber, string] & {
        from: string;
        timestamp: BigNumber;
        message: string;
      }
    >;
  };

  filters: {
    "Chirped(address,uint256,uint256,string)"(
      from?: string | null,
      id?: null,
      timestamp?: null,
      message?: null
    ): ChirpedEventFilter;
    Chirped(
      from?: string | null,
      id?: null,
      timestamp?: null,
      message?: null
    ): ChirpedEventFilter;
  };

  estimateGas: {
    chirp(
      message: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    chirps(arg0: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    chirp(
      message: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    chirps(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
