/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result, EventFragment } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export interface TweeterInterface extends utils.Interface {
  functions: {
    "tweet(string)": FunctionFragment;
    "tweets(uint256)": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "tweet", values: [string]): string;
  encodeFunctionData(
    functionFragment: "tweets",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "tweet", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "tweets", data: BytesLike): Result;

  events: {
    "Tweet(address,uint256,uint256,string)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "Tweet"): EventFragment;
}

export type TweetEvent = TypedEvent<
  [string, BigNumber, BigNumber, string],
  { from: string; id: BigNumber; timestamp: BigNumber; message: string }
>;

export type TweetEventFilter = TypedEventFilter<TweetEvent>;

export interface Tweeter extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: TweeterInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    tweet(
      message: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    tweets(arg0: BigNumberish, overrides?: CallOverrides): Promise<[string]>;
  };

  tweet(
    message: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  tweets(arg0: BigNumberish, overrides?: CallOverrides): Promise<string>;

  callStatic: {
    tweet(message: string, overrides?: CallOverrides): Promise<void>;

    tweets(arg0: BigNumberish, overrides?: CallOverrides): Promise<string>;
  };

  filters: {
    "Tweet(address,uint256,uint256,string)"(
      from?: string | null,
      id?: null,
      timestamp?: null,
      message?: null
    ): TweetEventFilter;
    Tweet(
      from?: string | null,
      id?: null,
      timestamp?: null,
      message?: null
    ): TweetEventFilter;
  };

  estimateGas: {
    tweet(
      message: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    tweets(arg0: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    tweet(
      message: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    tweets(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
