/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result, EventFragment } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export interface TweeterInterface extends utils.Interface {
  functions: {
    "tweet(string)": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "tweet", values: [string]): string;

  decodeFunctionResult(functionFragment: "tweet", data: BytesLike): Result;

  events: {
    "Tweet(string,address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "Tweet"): EventFragment;
}

export type TweetEvent = TypedEvent<
  [string, string],
  { message: string; from: string }
>;

export type TweetEventFilter = TypedEventFilter<TweetEvent>;

export interface Tweeter extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: TweeterInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    tweet(
      message: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  tweet(
    message: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    tweet(message: string, overrides?: CallOverrides): Promise<void>;
  };

  filters: {
    "Tweet(string,address)"(
      message?: string | null,
      from?: string | null
    ): TweetEventFilter;
    Tweet(message?: string | null, from?: string | null): TweetEventFilter;
  };

  estimateGas: {
    tweet(
      message: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    tweet(
      message: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
