/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { PublicChannel, PublicChannelInterface } from "../PublicChannel";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "from",
        type: "address",
      },
      {
        indexed: false,
        internalType: "string",
        name: "message",
        type: "string",
      },
    ],
    name: "PublicMessage",
    type: "event",
  },
];

export class PublicChannel__factory {
  static readonly abi = _abi;
  static createInterface(): PublicChannelInterface {
    return new utils.Interface(_abi) as PublicChannelInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): PublicChannel {
    return new Contract(address, _abi, signerOrProvider) as PublicChannel;
  }
}
